server:
  port: 8080
  servlet:
    context-path: /demo

spring:
    datasource:
      url: "jdbc:mysql://localhost:3306/demo"
      username: root
      password: 123456
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
    redis:
      host: localhost
      port: 6379

jwt:
  secret-key: "test_spring_boot_test_secret_key"
  access-token-exp: 6000 #seconds
  refresh-token-exp: 60000 #seconds